### ISSUE TITLE
Update check not functioning properly

### ISSUE THREAD

**Issue by KernelPone** [EncoreRP/encore_rpweapons#2]
The update check is not functioning properly because release v1.0.1 has shipped but the fxmanifest has the version still listed as v1.0.0 in the v1.0.1 package causing it to claim it is out of date, as well as show the wrong version number.

**Comment by encorecharles** [comment]
Resolved in release [v1.0.2](https://github.com/EncoreRP/encore_rpweapons/releases/tag/1.0.2). Thank you for the PR!
